---
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  sha: 63142f2d4ece8fd67cad3521c6e0c0f2bfef1c03
  hooks:
    - id: fix-encoding-pragma
      args:
        - '--pragma=# coding: utf-8'
      exclude: ^mylib/(board|qas)/gen/.*$
    - id: autopep8-wrapper
      args:
        - --in-place
        - --ignore=E722,E741,E501,E228,E226,E261,E266,E128,E402,E241
      exclude: ^mylib/(board|qas)/gen/.*$
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: pretty-format-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-xml
    - id: debug-statements
    - id: flake8
      args:
        - --ignore=E722,E741,E501,E228,E226,E261,E266,E128,E402,W503
        - --builtins=G,request
        - --jobs=1
      exclude: ^mylib/(board|qas)/gen/.*$
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
